### ISSUE TITLE
Program counter overflow check has off-by-one errors at end of 6502 memory

### ISSUE THREAD

**Issue by fjmilens3** [informedcitizenry/tiny6502#1]
I've been migrating over some assembly code to use tiny6502 and I've encountered what appear to be very specific off-by-one errors. The bounds check in `output_add_values` looks like it's too restrictive, reporting a program counter overflow when the last byte in 6502 memory is written.

This program should declare two bytes at the end of 6502 memory:

```
* = $FFFE

.WORD $FF
```

It produces:

```
% ./build/tiny6502 test1.asm
tiny6502 cross-assembler 0.2 (c) 2022 informedcitizenry
tiny6502 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions as defined in the LICENSE.
test1.asm(4:1): error: Program counter overflow.
.WORD $FF
^~~
1 errors.
```

This program should declare one byte at the end of 6502 memory:

```
* = $FFFF

.BYTE $FF
```

It produces:

```
% ./build/tiny6502 test2.asm
tiny6502 cross-assembler 0.2 (c) 2022 informedcitizenry
tiny6502 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions as defined in the LICENSE.
test2.asm(4:1): error: Program counter overflow.
.BYTE $FF
^~~
1 errors.
```

Based on my research, it appears that the `>=` comparison in `output_add_values` should be changed to `>` (https://github.com/informedcitizenry/tiny6502/blob/master/src/output.c#L61). 

This change would match the current implementation of `output_fill` where `>` is used (https://github.com/informedcitizenry/tiny6502/blob/master/src/output.c#L31).

I have a branch where I've fixed the error for my purposes, but I wanted to relay this upstream. I'll also send over my branch in case it's of use. It may also be that my analysis is in error, so you may want to check.

**Comment by informedcitizenry** [comment]
Thanks I'll take a look.

**Comment by informedcitizenry** [comment]
I saw your PR and merged it. Should be good.

**Comment by fjmilens3** [comment]
Thanks!
